{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fastapi-app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fastapi-app.labels" . | nindent 4 }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "fastapi-app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
