replicaCount: 2
image:
  repository: domniniquehallan/python-fastapi-app
  tag: 1.1.0
  pullPolicy: IfNotPresent
imagePullSecrets:
- name: dockerhub-creds
nameOverride: ""
fullnameOverride: ""
namespace: platform-demo
service:
  type: ClusterIP
  port: 80
  targetPort: 8000
ingress:
  enabled: true
  className: nginx
  host: fastapi-app.k8s.orb.local
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
probes:
  liveness:
    path: /api/v1/healthz
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
  readiness:
    path: /api/v1/ready
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL
env:
- name: PYTHONUNBUFFERED
  value: "1"
